SELECT ITEM_ID, ITEM_NAME , RARITY 
FROM ITEM_INFO
WHERE ITEM_INFO.ITEM_ID NOT IN (
    SELECT ITEM_TREE.PARENT_ITEM_ID
    FROM ITEM_TREE 
    where ITEM_TREE.PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_INFO.ITEM_ID DESC 

